"""Generates everything under data/synthetic/ (CLAUDE.md §9). Seeded and reproducible:
the same seed produces byte-identical files.

    python scripts/gen_synthetic.py                 # -> data/synthetic
    python scripts/gen_synthetic.py --out /tmp/syn  # somewhere else (tests use this)

Gold record ids in the benchmarks are computed by running the real parsers + chunker over the
generated documents, so they match what `python -m app.ingest.cli` loads.
"""
from __future__ import annotations

import argparse
import random
import re
import shutil
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:  # allow `python scripts/gen_synthetic.py`
    sys.path.insert(0, str(REPO_ROOT))

from app.core.config import get_settings
from app.ingest.adapters.base import TABLE_COLUMNS
from app.ingest.chunker import Chunk, chunk_text
from app.ingest.parsers import parse_file
from scripts.synth import benchmarks, content, records, writers

SEED = 20260101
GENERATED = ("docs", "tables", "scenarios", "past_queries.csv", "router_prompts.jsonl",
             "router_scenarios.jsonl", "qa_benchmark.jsonl", "pricing.yaml", "README.md")

PRICING = {
    "note": "SYNTHETIC. Simulated metered pricing for the self-hosted remote tier (ADR-1); no real provider.",
    "currency": "INR",
    "remote_tier": {"input_per_1k_tokens": 0.25, "output_per_1k_tokens": 1.00, "min_charge_per_request": 0.02},
    "local_tier": {"input_per_1k_tokens": 0.0, "output_per_1k_tokens": 0.0},
    "quota": {"unit": "requests", "daily_limit": benchmarks.DAILY_QUOTA},
    "network": {"base_rtt_ms": 120, "payload_kb_per_request": 4},
}


def _documents() -> list[tuple[str, str, str, list, str]]:
    """-> [(doc_id, title, doc_type, blocks, format)]"""
    docs = []
    for c in content.COURSES:
        fmt = content.SYLLABUS_FORMAT.get(c["code"], "md")
        docs.append((f"syllabus_{c['code'].lower()}", f"{c['code']} {c['title']} Syllabus", "syllabus",
                     content.syllabus_blocks(c), fmt))
    docs.append(("faq", "Frequently Asked Questions", "faq", content.faq_blocks(), "md"))
    for doc_id, title, blocks, fmt in content.POLICIES:
        docs.append((doc_id, title, "policy", blocks, fmt))
    docs.append(("notice_hostel_w32", "Hostel Notice Board - Week 32", "other", content.INJECTION_NOTICE, "md"))
    return docs


def _write_docs(out: Path) -> list[dict]:
    docs_dir = out / "docs"
    docs_dir.mkdir(parents=True)
    manifest = []
    writer = {"md": writers.write_markdown, "pdf": writers.write_pdf, "docx": writers.write_docx}
    for doc_id, title, doc_type, blocks, fmt in _documents():
        file = f"{doc_id}.{fmt}"
        writer[fmt](docs_dir / file, blocks)
        manifest.append({"doc_id": doc_id, "title": title, "doc_type": doc_type, "file": file})
    (docs_dir / "manifest.yaml").write_text(
        "# SYNTHETIC documents. Read by app/ingest/adapters/synthetic.py.\n"
        + yaml.safe_dump({"documents": manifest}, sort_keys=False, allow_unicode=True),
        encoding="utf-8", newline="\n")
    return manifest


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().lower()


def _make_resolver(out: Path, manifest: list[dict]) -> benchmarks.Resolver:
    cfg = get_settings().qa.chunking
    chunks: dict[str, list[Chunk]] = {}
    for entry in manifest:
        text = parse_file(out / "docs" / entry["file"])
        chunks[entry["doc_id"]] = chunk_text(entry["doc_id"], text, cfg.size_tokens, cfg.overlap_tokens)

    def resolve(doc_id: str, evidence: str) -> str:
        needle = _norm(evidence)
        for ch in chunks[doc_id]:
            if needle in _norm(ch.text):
                return ch.chunk_id
        raise ValueError(f"evidence not found in any chunk of {doc_id}: {evidence!r}")

    return resolve


def _readme(rec: records.Records, counts: dict[str, int]) -> str:
    edge = "\n".join(f"| `{sid}` | {note} |" for sid, note in rec.edge_cases.items())
    table = "\n".join(f"| {name} | {n} |" for name, n in counts.items())
    return f"""# Synthetic data (NOT real AMYPO data)

Generated by `python scripts/gen_synthetic.py` (seed {SEED}). Every file here is synthetic and exists
so the platform can be built and tested before the organiser data arrives. Regenerate instead of editing.
Load it into the database with `python -m app.ingest.cli --db-url mysql://user:pass@host:3306/amypo`.

| Set | Rows |
|---|---|
{table}

## Layout

- `docs/`: 8 syllabi, FAQ, 5 policies and a hostel notice with an embedded prompt-injection line.
  Mixed formats (markdown, PDF, DOCX) to exercise every parser. `docs/manifest.yaml` lists them.
- `tables/`: one CSV per structured table (students, grades, attendance, placement criteria, ...).
- `past_queries.csv`: FAQ paraphrase clusters (semantic cache, offline fallback).
- `router_prompts.jsonl`: prompts with ground-truth complexity; hints are sometimes wrong on purpose.
- `scenarios/*.csv` + `router_scenarios.jsonl`: resource traces and optimal routes
  (rule table in `app/eval/README.md`).
- `qa_benchmark.jsonl`: questions with expected answers, gold record ids, `type` and `expect`
  (answer / abstain / refuse).
- `pricing.yaml`: simulated remote-tier pricing and quota.

## Placement edge cases (against Zoho SDE: CGPA 7.5, 0 backlogs, 75% attendance, DSA 3, Java 3, SQL 2)

| Student | Case |
|---|---|
{edge}
"""


def generate(out: Path, seed: int = SEED) -> dict[str, int]:
    out.mkdir(parents=True, exist_ok=True)
    for name in GENERATED:
        target = out / name
        if target.is_dir():
            shutil.rmtree(target)
        elif target.exists():
            target.unlink()

    manifest = _write_docs(out)
    resolve = _make_resolver(out, manifest)

    rec = records.build(seed)
    (out / "tables").mkdir()
    for table, cols in TABLE_COLUMNS.items():
        writers.write_csv(out / "tables" / f"{table}.csv", cols, rec.tables[table])

    rng = random.Random(seed + 1)
    prompts = benchmarks.router_prompts(rng)
    traces = benchmarks.scenarios(rng)
    thresholds = get_settings().router.thresholds.model_dump()
    labels = benchmarks.router_scenarios(rng, prompts, traces, thresholds)
    qa = benchmarks.qa_benchmark(rng, rec, resolve)
    past = benchmarks.past_queries(rng, resolve)

    writers.write_jsonl(out / "router_prompts.jsonl", prompts)
    (out / "scenarios").mkdir()
    for name, rows in traces.items():
        writers.write_csv(out / "scenarios" / f"{name}.csv", benchmarks.SCENARIO_COLUMNS, rows)
    writers.write_jsonl(out / "router_scenarios.jsonl", labels)
    writers.write_jsonl(out / "qa_benchmark.jsonl", qa)
    writers.write_csv(out / "past_queries.csv", ("query_id", "cluster_id", "query", "answer", "record_id"), past)
    (out / "pricing.yaml").write_text(yaml.safe_dump(PRICING, sort_keys=False), encoding="utf-8", newline="\n")

    counts = {"documents": len(manifest), **{t: len(rows) for t, rows in rec.tables.items()},
              "past_queries": len(past), "router_prompts": len(prompts), "scenarios": len(traces),
              "router_scenarios": len(labels), "qa_benchmark": len(qa)}
    (out / "README.md").write_text(_readme(rec, counts), encoding="utf-8", newline="\n")
    return counts


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description="Generate synthetic data (seeded, reproducible).")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "data" / "synthetic")
    ap.add_argument("--seed", type=int, default=SEED)
    args = ap.parse_args(argv)
    counts = generate(args.out, args.seed)
    width = max(len(k) for k in counts)
    print(f"gen_synthetic: wrote {args.out}")
    for name, n in counts.items():
        print(f"  {name:<{width}}  {n:>6}")


if __name__ == "__main__":
    main()
